### PR TITLE
Enable balances for OSC OnDemand

### PR DESCRIPTION
**Pull request by treydock**
Requires https://github.com/OSC/ood-dashboard/pull/483

### CODE REVIEW

**Comment by treydock** [comment]
This may have to wait till October which I think is when Client Services wants to warn people.

**Comment by treydock** [comment]
@ericfranz @MorganRodgers @johrstrom Client Services wants the bash warning deployed October 1st so I figured be good to get this deployed then too. We'll need this merged and tagged for testing after current test branch changes are merged to production tomorrow.

**Comment by treydock** [comment]
Adding this will enable negative balance warnings. Pretty sure the dashboard code had been deployed.

**Comment by ericfranz** [comment]
Dashboard code has not been deployed. But I think these will just be ignored. https://github.com/OSC/ood-dashboard/releases/tag/v1.36.0 was intentionally left out of the rpm builds because that was also included with other "feature" additions and was more than we felt safe including in a patch release even though there is a feature flag for it.

After we release the patch release we can update ondemand latest with these changes.

**Comment by treydock** [comment]
As long as the balance stuff goes out soonish, tomorrow is when OSC starts enforcing balances so be good to have warnings besides ones I'm deploying for shell logins.

**Pull request merged**
