### PR TITLE
Allow job-pod-reaper to see OnDemand Kubernetes namespaces

### PR DESCRIPTION
**Pull request by treydock**

### CODE REVIEW

**Comment by johrstrom** [comment]
This files is meant for bootstrapping users. Shouldn't this be with the system ymls held in code osu edu?

**Comment by treydock** [comment]
No, because it's done on a per-namespace basis.  If we do it for the central config then we have to authorize job-pod-reaper on every namespace which I don't want to do. I want this RoleBinding added to every OnDemand namespace, and this is the only place to do that.

**Review by johrstrom — APPROVED** [review]
Oh I see. yea the ClusterRole `job-pod-reaper` is the global bit.

**Comment by treydock** [comment]
In case your curious, this is the RBAC deployed centrally: https://github.com/treydock/job-pod-reaper/blob/main/install/namespace-rbac.yaml

**Pull request merged**
