### PR TITLE
Replace OSC logo with high resolution SVG version

### PR DESCRIPTION
**Pull request by msquee**
This PR replaces the current OSC logo (24 kB) with a high resolution SVG (17 kB)

**PNG**
image

**SVG**
image

### CODE REVIEW

**Comment by msquee** [comment]
@ericfranz https://github.com/OSC/ondemand/blob/master/apps/dashboard/app/views/layouts/application.html.erb#L22 will need modified to support setting a width on the image or else this SVG would take up the entire width of the container

**Comment by ericfranz** [comment]
Open an issue in the ondemand repo for that. In the interim the image tag for the logo ends up being:

    logo

I think `?timestamp=1592924086` is just a cheap cache bust. In short term change https://github.com/OSC/osc-ood-config/blob/aec69388b2e08093b5a8ddedfc243bfdebb47aa1/ondemand.osc.edu/locales/en.yml#L4 to a custom image tag that loads logo.svg and then you can set the width in a style attribute.

**Comment by ericfranz** [comment]
Set OOD_DASHBOARD_LOGO_HEIGHT

**Comment by msquee** [comment]
@ericfranz Can this be merged in?

**Comment by johrstrom** [comment]
I need to deploy a new version today/tomorrow, so I'll check this out now.

**Comment by johrstrom** [comment]
This works for me!

**Pull request merged**
